### ISSUE TITLE
Code Completeness Checklist

### ISSUE THREAD

**Issue by cannin** [cannin/graph_neural_network_drug_response#4]
@inoue0426 this will be our guide for documentation of the final project. As you document/commit, keep these things in mind.  

* [x] Dependencies: does a repository have information on dependencies or instructions on how to set up the environment?
* [x] Training scripts: does a repository contain a way to train/fit the model(s) described in the paper?
* [x] Evaluation scripts: does a repository contain a script to calculate the performance of the trained model(s) or run experiments on models?
* [x] Pretrained models: does a repository provide free access to pretrained model weights?
* [x] Results: does a repository contain a table/plot of main results and a script to reproduce those results?

**Comment by inoue0426** [comment]
Hi @cannin 

I set up the template.
However, the website cannot show the 2022's article though it can show 2021 one.
https://lunean.com/graph_neural_network_drug_response/
Do you know why this is happening?
